"""empty message

Revision ID: 7f887bd3dcd2
Revises: f4196f1cd122
Create Date: 2022-11-07 00:48:39.119223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f887bd3dcd2'
down_revision = 'f4196f1cd122'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False))
    op.drop_column('transfers', 'transfer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('transfer_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))
    op.drop_column('transfers', 'id')
    # ### end Alembic commands ###
